# Generated by Django 3.0.5 on 2021-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinup',
            name='password',
            field=models.CharField(max_length=122),
        ),
    ]
