# Generated by Django 3.0.5 on 2021-02-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
