# Generated by Django 3.0.5 on 2021-03-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0005_auto_20210225_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='login_email',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='login_password',
        ),
    ]
