# Generated by Django 3.0.5 on 2021-03-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0007_auto_20210301_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='login_username',
            new_name='login_email',
        ),
        migrations.RenameField(
            model_name='sinup',
            old_name='username',
            new_name='email',
        ),
    ]
