# Generated by Django 3.0.5 on 2021-03-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0008_auto_20210301_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='login_email',
            new_name='login_username',
        ),
        migrations.RenameField(
            model_name='sinup',
            old_name='name',
            new_name='username',
        ),
    ]
