# Generated by Django 3.0.5 on 2021-03-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0009_auto_20210302_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
