# Generated by Django 3.0.5 on 2021-03-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0010_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinup',
            old_name='username',
            new_name='name',
        ),
    ]
