# Generated by Django 3.0.5 on 2021-03-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0011_auto_20210302_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinup',
            name='username',
            field=models.CharField(default='naman12', max_length=122),
        ),
    ]
